# File: .github/workflows/firebase-hosting-merge.yml

name: Deploy Frontend to Firebase Hosting

on:
  push:
    branches:
      - main
    paths:
      - 'FE/**'
      - '.github/workflows/firebase-hosting-merge.yml'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: FE 

    steps:
      - uses: actions/checkout@v4

      - name: Install and Build
        run: npm ci && npm run build
        env:
          VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }}

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_ENGCHI_APP }}'
          channelId: live
          projectId: engchi-app